// import './icons/plus.svg?sprite=true'
// import './icons/cross.svg?sprite=true'
// import './icons/caret-down.svg?sprite=true'
// import './icons/chevron-down.svg?sprite=true'
// import './icons/upload-circle.svg?sprite=true'
// import './icons/upload-cloud.svg?sprite=true'

// Generic
import './assets/images/icons/plus.svg?sprite=true'
import './assets/images/icons/camera.svg?sprite=true'
import './assets/images/icons/cross.svg?sprite=true'
import './assets/images/icons/back-arrow.svg?sprite=true'
import './assets/images/icons/move.svg?sprite=true'
import './assets/images/icons/move-v.svg?sprite=true'
import './assets/images/icons/trash.svg?sprite=true'
import './assets/images/icons/ellipsis-v.svg?sprite=true'
import './assets/images/icons/ellipsis-v-solid.svg?sprite=true'
import './assets/images/icons/ellipsis-h.svg?sprite=true'
import './assets/images/icons/ellipsis-h-solid.svg?sprite=true'
import './assets/images/icons/exclamation-triangle.svg?sprite=true'
import './assets/images/icons/settings.svg?sprite=true'
import './assets/images/icons/image-placeholder.svg?sprite=true'
import './assets/images/icons/video-placeholder.svg?sprite=true'
import './assets/images/icons/upload-circle.svg?sprite=true'
import './assets/images/icons/upload-cloud.svg?sprite=true'

// Designer elements
import './assets/images/designer/text.svg?sprite=true'
import './assets/images/designer/heading.svg?sprite=true'
import './assets/images/designer/button.svg?sprite=true'
import './assets/images/designer/image.svg?sprite=true'
import './assets/images/designer/video.svg?sprite=true'
import './assets/images/designer/banner.svg?sprite=true'
import './assets/images/designer/card.svg?sprite=true'
import './assets/images/designer/carousel.svg?sprite=true'
import './assets/images/designer/spacer.svg?sprite=true'
import './assets/images/designer/grid.svg?sprite=true'
import './assets/images/designer/grid-masonry.svg?sprite=true'
import './assets/images/designer/email.svg?sprite=true'
import './assets/images/designer/instagram.svg?sprite=true'
import './assets/images/designer/twitter.svg?sprite=true'

// Designer templates
import './assets/images/designer/template-blank.svg?sprite=true'
import './assets/images/designer/template-banner-1-column.svg?sprite=true'
import './assets/images/designer/template-banner-2-column.svg?sprite=true'
import './assets/images/designer/template-banner-3-column.svg?sprite=true'
import './assets/images/designer/template-grid-2-column.svg?sprite=true'
import './assets/images/designer/template-grid-3-column.svg?sprite=true'
import './assets/images/designer/template-details-2-column.svg?sprite=true'
import './assets/images/designer/template-details-3-column.svg?sprite=true'
import './assets/images/designer/template-details-horizontal.svg?sprite=true'
