// import './icons/plus.svg'
// import './icons/cross.svg'
// import './icons/caret-down.svg'
// import './icons/chevron-down.svg'
// import './icons/upload-circle.svg'
// import './icons/upload-cloud.svg'

// Generic
import './assets/images/icons/plus.svg'
import './assets/images/icons/cross.svg'
import './assets/images/icons/back-arrow.svg'
import './assets/images/icons/move-v.svg'
import './assets/images/icons/trash.svg'
import './assets/images/icons/ellipsis-v.svg'
import './assets/images/icons/ellipsis-v-solid.svg'
import './assets/images/icons/ellipsis-h.svg'
import './assets/images/icons/ellipsis-h-solid.svg'
import './assets/images/icons/settings.svg'
import './assets/images/icons/image-placeholder.svg'
import './assets/images/icons/video-placeholder.svg'
import './assets/images/icons/upload-circle.svg'
import './assets/images/icons/upload-cloud.svg'

// Designer elements
import './assets/images/designer/text.svg'
import './assets/images/designer/heading.svg'
import './assets/images/designer/button.svg'
import './assets/images/designer/image.svg'
import './assets/images/designer/video.svg'
import './assets/images/designer/banner.svg'
import './assets/images/designer/card.svg'
import './assets/images/designer/carousel.svg'
import './assets/images/designer/spacer.svg'
import './assets/images/designer/grid.svg'
import './assets/images/designer/email.svg'

// Designer templates
import './assets/images/designer/template-blank.svg'
import './assets/images/designer/template-banner-1-column.svg'
import './assets/images/designer/template-banner-2-column.svg'
import './assets/images/designer/template-banner-3-column.svg'
import './assets/images/designer/template-grid-2-column.svg'
import './assets/images/designer/template-grid-3-column.svg'
import './assets/images/designer/template-details-2-column.svg'
import './assets/images/designer/template-details-3-column.svg'
import './assets/images/designer/template-details-horizontal.svg'
